var mongoose = require("mongoose");
var Schema = mongoose.Schema;

// This is a specific instance of a tile, generated by a admin for a specific player
var Tile = new Schema({
  tile_profile_id: { type: String },
  created_date: { type: Date, default: Date.now },
  total_minutes: { type: Number, default: 0 },
  color: { type: Number, default: 0 },
  entries: [Entry],
  goal_last_cycle_start: { type: Date, default: Date.now }
});

var Entry = new Schema({
  content: { type: String, required: true },
  comments: { type: String, default: '' },
  minutes: { type: Number },
  date: { type: Date }
});

module.exports = mongoose.model("Tile", Tile);
