const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const TileSchema = require('./TileSchema');

// * A TileSet contains identifying info about the tile set along
//   with an array of actual tiles
// * Each TileSet corresponds with a set of default tiles generated by one
//   profile_id

const TileSetSchema = new Schema({
  tile_set_name: String,
  tile_set_profile: String,
  tiles: [TileSchema],
  created_date: { type: Date, default: Date.now },
});

module.exports = TileSetSchema;
